apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    che.eclipse.org/checluster-defaults-cleanup: '{"containers.resources":"true","spec.components.dashboard.headerMessage":"true","spec.components.pluginRegistry.openVSXURL":"true","spec.devEnvironments.defaultComponents":"true","spec.devEnvironments.defaultEditor":"true","spec.devEnvironments.disableContainerBuildCapabilities":"true"}'
  creationTimestamp: "2026-04-14T04:24:21Z"
  finalizers:
  - checluster.che.eclipse.org
  - cheGateway.clusterpermissions.finalizers.che.eclipse.org
  - oauthclients.finalizers.che.eclipse.org
  - dashboard.clusterpermissions.finalizers.che.eclipse.org
  - container-build.finalizers.che.eclipse.org
  - consolelink.finalizers.che.eclipse.org
  generation: 3
  name: devspaces
  namespace: openshift-operators
  resourceVersion: "387364"
  uid: 957d618c-f7e5-4c30-b460-acbd2ec30571
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      deployment:
        containers:
        - env:
          - name: CHE_HIDE_EDITORS_BY_ID
            value: che-incubator/che-code-sshd/latest
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    containerRunConfiguration:
      containerSecurityContext:
        allowPrivilegeEscalation: true
        capabilities:
          add:
          - SETGID
          - SETUID
        procMount: Unmasked
      openShiftSecurityContextConstraint: container-run
      workspacesPodAnnotations:
        io.kubernetes.cri-o.Devices: /dev/fuse,/dev/net/tun
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    disableContainerRunCapabilities: true
    ignoredUnrecoverableEvents:
    - FailedScheduling
    maxNumberOfWorkspacesPerUser: -1
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    security: {}
    startTimeoutSeconds: 300
    storage:
      pvcStrategy: per-user
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO
status:
  chePhase: Active
  cheURL: https://devspaces.apps.cluster-zhssv.zhssv.sandbox245.opentlc.com
  cheVersion: 3.26.0
  devfileRegistryURL: ""
  gatewayPhase: Established
  pluginRegistryURL: https://devspaces.apps.cluster-zhssv.zhssv.sandbox245.opentlc.com/plugin-registry/v3
  workspaceBaseDomain: apps.cluster-zhssv.zhssv.sandbox245.opentlc.com
